	 '0') key___='<0>'                    ; key__s='<)>'                    ; key_a_='<a-0>'                  ; key_as='<a-)>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '1') key___='<1>'                    ; key__s='<!>'                    ; key_a_='<a-1>'                  ; key_as='<a-!>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '2') key___='<2>'                    ; key__s='<@>'                    ; key_a_='<a-2>'                  ; key_as='<a-@>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '3') key___='<3>'                    ; key__s='<#>'                    ; key_a_='<a-3>'                  ; key_as='<a-#>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '4') key___='<4>'                    ; key__s='<$>'                    ; key_a_='<a-4>'                  ; key_as='<a-$>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '5') key___='<5>'                    ; key__s='<%>'                    ; key_a_='<a-5>'                  ; key_as='<a-%>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '6') key___='<6>'                    ; key__s='<^>'                    ; key_a_='<a-6>'                  ; key_as='<a-^>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '7') key___='<7>'                    ; key__s='<&>'                    ; key_a_='<a-7>'                  ; key_as='<a-&>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '8') key___='<8>'                    ; key__s='<*>'                    ; key_a_='<a-8>'                  ; key_as='<a-*>'                  ; key_c_=''                       ; key_cs=''                       ;;
	 '9') key___='<9>'                    ; key__s='<(>'                    ; key_a_='<a-9>'                  ; key_as='<a-(>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'10') key___='<F1>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'11') key___='<F2>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'12') key___='<F3>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'13') key___='<F4>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'14') key___='<F5>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'15') key___='<F6>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'16') key___='<F7>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'17') key___='<F8>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'18') key___='<F9>'                   ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'19') key___='<F10>'                  ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'20') key___='<F11>'                  ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'21') key___='<F12>'                  ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'22') key___='<left>'                 ; key__s='<s-left>'               ; key_a_='<a-left>'               ; key_as='<a-s-left>'             ; key_c_='<c-left>'               ; key_cs='<c-s-left>'             ;;
	'23') key___='<right>'                ; key__s='<s-right>'              ; key_a_='<a-right>'              ; key_as='<a-s-right>'            ; key_c_='<c-right>'              ; key_cs='<c-s-right>'            ;;
	'24') key___='<up>'                   ; key__s='<s-up>'                 ; key_a_='<a-up>'                 ; key_as='<a-s-up>'               ; key_c_='<c-up>'                 ; key_cs='<c-s-up>'               ;;
	'25') key___='<down>'                 ; key__s='<s-down>'               ; key_a_='<a-down>'               ; key_as='<a-s-down>'             ; key_c_='<c-down>'               ; key_cs='<c-s-down>'             ;;
	'26') key___='<pageup>'               ; key__s='<s-pageup>'             ; key_a_='<a-pageup>'             ; key_as='<a-s-pageup>'           ; key_c_='<c-pageup>'             ; key_cs='<c-s-pageup>'           ;;
	'27') key___='<pagedown>'             ; key__s='<s-pagedown>'           ; key_a_='<a-pagedown>'           ; key_as='<a-s-pagedown>'         ; key_c_='<c-pagedown>'           ; key_cs='<c-s-pagedown>'         ;;
	'28') key___='<home>'                 ; key__s='<s-home>'               ; key_a_='<a-home>'               ; key_as='<a-s-home>'             ; key_c_='<c-home>'               ; key_cs='<c-s-home>'             ;;
	'29') key___='<end>'                  ; key__s='<s-end>'                ; key_a_='<a-end>'                ; key_as='<a-s-end>'              ; key_c_='<c-end>'                ; key_cs='<c-s-end>'              ;;
	'30') key___='<tab>'                  ; key__s='<s-tab>'                ; key_a_='<a-tab>'                ; key_as='<a-s-tab>'              ; key_c_=''                       ; key_cs=''                       ;;
	'31') key___='<backspace>'            ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'32') key___='<del>'                  ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'33') key___='<space>'                ; key__s=''                       ; key_a_='<a-space>'              ; key_as=''                       ; key_c_='<c-space>'              ; key_cs=''                       ;;
	'34') key___='<esc>'                  ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'35') key___='<ret>'                  ; key__s=''                       ; key_a_=''                       ; key_as=''                       ; key_c_=''                       ; key_cs=''                       ;;
	'36') key___='<j>'                    ; key__s='<J>'                    ; key_a_='<a-j>'                  ; key_as='<a-J>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'37') key___='<l>'                    ; key__s='<L>'                    ; key_a_='<a-l>'                  ; key_as='<a-L>'                  ; key_c_='<c-l>'                  ; key_cs=''                       ;;
	'38') key___='<i>'                    ; key__s='<I>'                    ; key_a_='<a-i>'                  ; key_as='<a-I>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'39') key___='<k>'                    ; key__s='<K>'                    ; key_a_='<a-k>'                  ; key_as='<a-K>'                  ; key_c_='<c-k>'                  ; key_cs=''                       ;;
	'40') key___='<u>'                    ; key__s='<U>'                    ; key_a_='<a-u>'                  ; key_as='<a-U>'                  ; key_c_='<c-u>'                  ; key_cs=''                       ;;
	'41') key___='<o>'                    ; key__s='<O>'                    ; key_a_='<a-o>'                  ; key_as='<a-O>'                  ; key_c_='<c-o>'                  ; key_cs=''                       ;;
	'42') key___='<h>'                    ; key__s='<H>'                    ; key_a_='<a-h>'                  ; key_as='<a-H>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'43') key___='<n>'                    ; key__s='<N>'                    ; key_a_='<a-n>'                  ; key_as='<a-N>'                  ; key_c_='<c-n>'                  ; key_cs=''                       ;;
	'44') key___='<y>'                    ; key__s='<Y>'                    ; key_a_='<a-y>'                  ; key_as='<a-Y>'                  ; key_c_='<c-y>'                  ; key_cs=''                       ;;
	'45') key___='<m>'                    ; key__s='<M>'                    ; key_a_='<a-m>'                  ; key_as='<a-M>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'46') key___='<,>'                    ; key__s='<lt>'                   ; key_a_='<a-,>'                  ; key_as='<a-lt>'                 ; key_c_=''                       ; key_cs=''                       ;;
	'47') key___='<g>'                    ; key__s='<G>'                    ; key_a_='<a-g>'                  ; key_as='<a-G>'                  ; key_c_='<c-g>'                  ; key_cs=''                       ;;
	'48') key___='<s>'                    ; key__s='<S>'                    ; key_a_='<a-s>'                  ; key_as='<a-S>'                  ; key_c_='<c-s>'                  ; key_cs=''                       ;;
	'49') key___='<a>'                    ; key__s='<A>'                    ; key_a_='<a-a>'                  ; key_as='<a-A>'                  ; key_c_='<c-a>'                  ; key_cs=''                       ;;
	'50') key___='<[>'                    ; key__s='<{>'                    ; key_a_='<a-[>'                  ; key_as='<a-{>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'51') key___='<]>'                    ; key__s='<}>'                    ; key_a_='<a-]>'                  ; key_as='<a-}>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'52') key___='<d>'                    ; key__s='<D>'                    ; key_a_='<a-d>'                  ; key_as='<a-D>'                  ; key_c_='<c-d>'                  ; key_cs=''                       ;;
	'53') key___='<f>'                    ; key__s='<F>'                    ; key_a_='<a-f>'                  ; key_as='<a-F>'                  ; key_c_='<c-f>'                  ; key_cs=''                       ;;
	'54') key___='<e>'                    ; key__s='<E>'                    ; key_a_='<a-e>'                  ; key_as='<a-E>'                  ; key_c_='<c-e>'                  ; key_cs=''                       ;;
	'55') key___='<x>'                    ; key__s='<X>'                    ; key_a_='<a-x>'                  ; key_as='<a-X>'                  ; key_c_='<c-x>'                  ; key_cs=''                       ;;
	'56') key___='<c>'                    ; key__s='<C>'                    ; key_a_='<a-c>'                  ; key_as='<a-C>'                  ; key_c_='<c-c>'                  ; key_cs=''                       ;;
	'57') key___='<v>'                    ; key__s='<V>'                    ; key_a_='<a-v>'                  ; key_as='<a-V>'                  ; key_c_='<c-v>'                  ; key_cs=''                       ;;
	'58') key___='<w>'                    ; key__s='<W>'                    ; key_a_='<a-w>'                  ; key_as='<a-W>'                  ; key_c_='<c-w>'                  ; key_cs=''                       ;;
	'59') key___='<p>'                    ; key__s='<P>'                    ; key_a_='<a-p>'                  ; key_as='<a-P>'                  ; key_c_='<c-p>'                  ; key_cs=''                       ;;
	'60') key___='<b>'                    ; key__s='<B>'                    ; key_a_='<a-b>'                  ; key_as='<a-B>'                  ; key_c_='<c-b>'                  ; key_cs=''                       ;;
	'61') key___='<semicolon>'            ; key__s='<:>'                    ; key_a_='<a-semicolon>'          ; key_as='<a-:>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'62') key___='<`>'                    ; key__s='<~>'                    ; key_a_='<a-`>'                  ; key_as='<a-~>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'63') key___='<z>'                    ; key__s='<Z>'                    ; key_a_='<a-z>'                  ; key_as='<a-Z>'                  ; key_c_='<c-z>'                  ; key_cs=''                       ;;
	'64') key___='<r>'                    ; key__s='<R>'                    ; key_a_='<a-r>'                  ; key_as='<a-R>'                  ; key_c_='<c-r>'                  ; key_cs=''                       ;;
	'65') key___='<t>'                    ; key__s='<T>'                    ; key_a_='<a-t>'                  ; key_as='<a-T>'                  ; key_c_='<c-t>'                  ; key_cs=''                       ;;
	'66') key___='<.>'                    ; key__s='<gt>'                   ; key_a_='<a-.>'                  ; key_as='<a-gt>'                 ; key_c_=''                       ; key_cs=''                       ;;
	'67') key___='</>'                    ; key__s='<?>'                    ; key_a_='<a-/>'                  ; key_as='<a-?>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'68') key___='<q>'                    ; key__s='<Q>'                    ; key_a_='<a-q>'                  ; key_as='<a-Q>'                  ; key_c_='<c-q>'                  ; key_cs=''                       ;;
	'69') key___='<\>'                    ; key__s='<|>'                    ; key_a_='<a-\>'                  ; key_as='<a-|>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'70') key___='<minus>'                ; key__s='<_>'                    ; key_a_='<a-minus>'              ; key_as='<a-_>'                  ; key_c_=''                       ; key_cs=''                       ;;
	'71') key___='<=>'                    ; key__s='<plus>'                 ; key_a_='<a-=>'                  ; key_as='<a-plus>'               ; key_c_=''                       ; key_cs=''                       ;;
	'72') key___="<'>"                    ; key__s='<">'                    ; key_a_="<a-'>"                  ; key_as='<a-">'                  ; key_c_=''                       ; key_cs=''                       ;;

	 '0') nor___='0'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '1') nor___='1'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '2') nor___='2'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '3') nor___='3'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '4') nor___='4'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '5') nor___='5'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '6') nor___='6'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '7') nor___='7'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '8') nor___='8'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	 '9') nor___='9'                      ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'10') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'11') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'12') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'13') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'14') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'15') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'16') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'17') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'18') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'19') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'20') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'21') nor___=''                       ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'22') nor___='<h>'                    ; nor__s='<H>'                    ; nor_a_='<lt>'                   ; nor_as='<a-lt>'                 ; nor_c_='<b>'                    ; nor_cs='<B>'                    ;;
	'23') nor___='<l>'                    ; nor__s='<L>'                    ; nor_a_='<gt>'                   ; nor_as='<a-gt>'                 ; nor_c_='<e>'                    ; nor_cs='<E>'                    ;;
	'24') nor___='<k>'                    ; nor__s='<K>'                    ; nor_a_=''                       ; nor_as=''                       ; nor_c_='<k>'                    ; nor_cs='<K>'                    ;;
	'25') nor___='<j>'                    ; nor__s='<J>'                    ; nor_a_=''                       ; nor_as=''                       ; nor_c_='<j>'                    ; nor_cs='<J>'                    ;;
	'26') nor___='<c-b>'                  ; nor__s='<c-b>'                  ; nor_a_=''                       ; nor_as=''                       ; nor_c_='<c-u>'                  ; nor_cs='<c-u>'                  ;;
	'27') nor___='<c-f>'                  ; nor__s='<c-f>'                  ; nor_a_=''                       ; nor_as=''                       ; nor_c_='<c-d>'                  ; nor_cs='<c-d>'                  ;;
	'28') nor___='<a-h>'                  ; nor__s='<a-H>'                  ; nor_a_=''                       ; nor_as=''                       ; nor_c_='<g><g>'                 ; nor_cs='<G><g>'                 ;;
	'29') nor___='<a-l>'                  ; nor__s='<a-L>'                  ; nor_a_=''                       ; nor_as=''                       ; nor_c_='<g><e>'                 ; nor_cs='<G><e>'                 ;;
	'30') nor___=': buffer-previous<ret>' ; nor__s=': buffer-next<ret>'     ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'31') nor___='<;><h><a-d>'            ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'32') nor___='<;><a-d>'               ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'33') nor___=': bkey-menu<ret>'       ; nor__s=''                       ; nor_a_=': bkey-menuex<ret>'     ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'34') nor___='<;>'                    ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'35') nor___='<ret>'                  ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'36') nor___='<h>'                    ; nor__s='<a-h>'                  ; nor_a_='<H>'                    ; nor_as='<a-H>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'37') nor___='<l>'                    ; nor__s='<a-l>'                  ; nor_a_='<L>'                    ; nor_as='<a-L>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'38') nor___='<k>'                    ; nor__s='<[>p'                   ; nor_a_='<K>'                    ; nor_as='<{>p'                   ; nor_c_=''                       ; nor_cs=''                       ;;
	'39') nor___='<j>'                    ; nor__s='<]>p'                   ; nor_a_='<J>'                    ; nor_as='<}>p'                   ; nor_c_=''                       ; nor_cs=''                       ;;
	'40') nor___='<b>'                    ; nor__s='<a-b>'                  ; nor_a_='<B>'                    ; nor_as='<a-B>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'41') nor___='<e>'                    ; nor__s='<a-e>'                  ; nor_a_='<E>'                    ; nor_as='<a-E>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'42') nor___='</>'                    ; nor__s='<a-/>'                  ; nor_a_='<?>'                    ; nor_as='<a-?>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'43') nor___='<n>'                    ; nor__s='<a-n>'                  ; nor_a_='<N>'                    ; nor_as='<a-N>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'44') nor___='<f>'                    ; nor__s='<a-f>'                  ; nor_a_='<F>'                    ; nor_as='<a-F>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'45') nor___='<m>'                    ; nor__s='<a-m>'                  ; nor_a_='<M>'                    ; nor_as='<a-M>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'46') nor___='<z>'                    ; nor__s='<Z>'                    ; nor_a_=''                       ; nor_as='<c-s>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'47') nor___='<)>'                    ; nor__s='<(>'                    ; nor_a_='<a-)>'                  ; nor_as='<a-(>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'48') nor___='<a-x>'                  ; nor__s='<%>'                    ; nor_a_='<a-x>'                  ; nor_as='<a-X>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'49') nor___='<a-i>'                  ; nor__s='<a-a>'                  ; nor_a_='<a-;>'                  ; nor_as='<a-:>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'50') nor___='<a-[>'                  ; nor__s='['                      ; nor_a_='<a-{>'                  ; nor_as='{'                      ; nor_c_=''                       ; nor_cs=''                       ;;
	'51') nor___='<a-]>'                  ; nor__s=']'                      ; nor_a_='<a-}>'                  ; nor_as='}'                      ; nor_c_=''                       ; nor_cs=''                       ;;
	'52') nor___=': bkey-ins i<ret>'      ; nor__s='<A>'                    ; nor_a_=': bkey-ins i<ret>'      ; nor_as='<I>'                    ; nor_c_=''                       ; nor_cs=''                       ;;
	'53') nor___='<u>'                    ; nor__s='<U>'                    ; nor_a_='<c-o>'                  ; nor_as='<c-i>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'54') nor___='<a-c>'                  ; nor__s='<a-l><a-c>'             ; nor_a_='<r>'                    ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'55') nor___='<d>'                    ; nor__s='<a-l><y>'               ; nor_a_='<a-d>'                  ; nor_as='<a-l><a-d>'             ; nor_c_=''                       ; nor_cs=''                       ;;
	'56') nor___='<y>'                    ; nor__s='<a-l><y>'               ; nor_a_='<y>'                    ; nor_as='<a-L><y>'               ; nor_c_=''                       ; nor_cs=''                       ;;
	'57') nor___=': bkey-ins p<ret>'      ; nor__s='<R>'                    ; nor_a_=': bkey-ins pe<ret>'     ; nor_as='<R>'                    ; nor_c_=''                       ; nor_cs=''                       ;;
	'58') nor___='<space>'                ; nor__s='<a-space>'              ; nor_a_='<_>'                    ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'59') nor___='<a-o>'                  ; nor__s='<a-O>'                  ; nor_a_='<C>'                    ; nor_as='<a-C>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'60') nor___='<a-J>'                  ; nor__s='<a-_>'                  ; nor_a_='<a-j>'                  ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'61') nor___='<:>'                    ; nor__s=': bkey-ins c<ret>'      ; nor_a_='<a-|>'                  ; nor_as='<|>'                    ; nor_c_=''                       ; nor_cs=''                       ;;
	'62') nor___=':terminal '             ; nor__s=': bkey-open-term<ret>'  ; nor_a_='<a-|>'                  ; nor_as='<|>'                    ; nor_c_=''                       ; nor_cs=''                       ;;
	'63') nor___='<u>'                    ; nor__s='<U>'                    ; nor_a_='<a-u>'                  ; nor_as='<a-U>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'64') nor___='<a-.>'                  ; nor__s='<.>'                    ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'65') nor___='<q>'                    ; nor__s='<Q>'                    ; nor_a_=''                       ; nor_as='<esc>'                  ; nor_c_=''                       ; nor_cs=''                       ;;
	'66') nor___=': write<ret>'           ; nor__s=':terminal '             ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'67') nor___='<">'                    ; nor__s='<\>'                    ; nor_a_=': comment-line<ret>'    ; nor_as=': comment-block<ret>'   ; nor_c_=''                       ; nor_cs=''                       ;;
	'68') nor___='<,>'                    ; nor__s=''                       ; nor_a_=''                       ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'69') nor___=': bkey-view<ret>'       ; nor__s=': bkey-view-lock<ret>'  ; nor_a_=': bkey-linewrap<ret>'   ; nor_as=': bkey-linewrap<ret>'   ; nor_c_=''                       ; nor_cs=''                       ;;
	'70') nor___='<lt>'                   ; nor__s='<`>'                    ; nor_a_='<a-lt>'                 ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'71') nor___='<gt>'                   ; nor__s='<~>'                    ; nor_a_='<a-gt>'                 ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;
	'72') nor___='<&>'                    ; nor__s='<a-`>'                  ; nor_a_='<a-&>'                  ; nor_as=''                       ; nor_c_=''                       ; nor_cs=''                       ;;

	 '0') ins___=''                       ; ins__s=''                       ;;
	 '1') ins___=''                       ; ins__s=''                       ;;
	 '2') ins___=''                       ; ins__s=''                       ;;
	 '3') ins___=''                       ; ins__s=''                       ;;
	 '4') ins___=''                       ; ins__s=''                       ;;
	 '5') ins___=''                       ; ins__s=''                       ;;
	 '6') ins___=''                       ; ins__s=''                       ;;
	 '7') ins___=''                       ; ins__s=''                       ;;
	 '8') ins___=''                       ; ins__s=''                       ;;
	 '9') ins___=''                       ; ins__s=''                       ;;
	'10') ins___=''                       ; ins__s=''                       ;;
	'11') ins___=''                       ; ins__s=''                       ;;
	'12') ins___=''                       ; ins__s=''                       ;;
	'13') ins___=''                       ; ins__s=''                       ;;
	'14') ins___=''                       ; ins__s=''                       ;;
	'15') ins___=''                       ; ins__s=''                       ;;
	'16') ins___=''                       ; ins__s=''                       ;;
	'17') ins___=''                       ; ins__s=''                       ;;
	'18') ins___=''                       ; ins__s=''                       ;;
	'19') ins___=''                       ; ins__s=''                       ;;
	'20') ins___=''                       ; ins__s=''                       ;;
	'21') ins___=''                       ; ins__s=''                       ;;
	'22') ins___='<;><lt>'                ; nor__s='<;><a-lt>'              ;;
	'23') ins___='<;><gt>'                ; nor__s='<;><a-gt>'              ;;
	'24') ins___=''                       ; ins__s=''                       ;;
	'25') ins___=''                       ; ins__s=''                       ;;
	'26') ins___=''                       ; ins__s=''                       ;;
	'27') ins___=''                       ; ins__s=''                       ;;
	'28') ins___=''                       ; ins__s=''                       ;;
	'29') ins___=''                       ; ins__s=''                       ;;
	'30') ins___=''                       ; ins__s=''                       ;;
	'31') ins___='<backspace>'            ; ins__s=''                       ;;
	'32') ins___='<del>'                  ; ins__s=''                       ;;
	'33') ins___=''                       ; ins__s=''                       ;;
	'34') ins___='<esc>'                  ; ins__s=''                       ;;
	'35') ins___='<ret>'                  ; ins__s=''                       ;;
	'36') ins___='<left>'                 ; ins__s='<home>'                 ;;
	'37') ins___='<right>'                ; ins__s='<end>'                  ;;
	'38') ins___='<up>'                   ; ins__s=''                       ;;
	'39') ins___='<down>'                 ; ins__s=''                       ;;
	'40') ins___=''                       ; ins__s=''                       ;;
	'41') ins___=''                       ; ins__s=''                       ;;
	'42') ins___=''                       ; ins__s=''                       ;;
	'43') ins___=''                       ; ins__s=''                       ;;
	'44') ins___=''                       ; ins__s=''                       ;;
	'45') ins___=''                       ; ins__s=''                       ;;
	'46') ins___=''                       ; ins__s=''                       ;;
	'47') ins___=''                       ; ins__s=''                       ;;
	'48') ins___='<a-;>'                  ; ins__s='<esc>'                  ;;
	'49') ins___=''                       ; ins__s=''                       ;;
	'50') ins___=''                       ; ins__s=''                       ;;
	'51') ins___=''                       ; ins__s=''                       ;;
	'52') ins___='<c-v>'                  ; ins__s='<c-u>'                  ;;
	'53') ins___=''                       ; ins__s=''                       ;;
	'54') ins___='<c-r>'                  ; ins__s=''                       ;;
	'55') ins___=''                       ; ins__s=''                       ;;
	'56') ins___=''                       ; ins__s=''                       ;;
	'57') ins___=''                       ; ins__s=''                       ;;
	'58') ins___=''                       ; ins__s=''                       ;;
	'59') ins___=''                       ; ins__s=''                       ;;
	'60') ins___=''                       ; ins__s=''                       ;;
	'61') ins___=''                       ; ins__s=''                       ;;
	'62') ins___=''                       ; ins__s=''                       ;;
	'63') ins___=''                       ; ins__s=''                       ;;
	'64') ins___=''                       ; ins__s=''                       ;;
	'65') ins___=''                       ; ins__s=''                       ;;
	'66') ins___=''                       ; ins__s=''                       ;;
	'67') ins___='<c-o>'                  ; ins__s='<c-x>'                  ;;
	'68') ins___=''                       ; ins__s=''                       ;;
	'69') ins___=''                       ; ins__s=''                       ;;
	'70') ins___=''                       ; ins__s=''                       ;;
	'71') ins___=''                       ; ins__s=''                       ;;
	'72') ins___=''                       ; ins__s=''                       ;;

	 '0') pro___=''                       ; pro__s=''                       ;;
	 '1') pro___=''                       ; pro__s=''                       ;;
	 '2') pro___=''                       ; pro__s=''                       ;;
	 '3') pro___=''                       ; pro__s=''                       ;;
	 '4') pro___=''                       ; pro__s=''                       ;;
	 '5') pro___=''                       ; pro__s=''                       ;;
	 '6') pro___=''                       ; pro__s=''                       ;;
	 '7') pro___=''                       ; pro__s=''                       ;;
	 '8') pro___=''                       ; pro__s=''                       ;;
	 '9') pro___=''                       ; pro__s=''                       ;;
	'10') pro___=''                       ; pro__s=''                       ;;
	'11') pro___=''                       ; pro__s=''                       ;;
	'12') pro___=''                       ; pro__s=''                       ;;
	'13') pro___=''                       ; pro__s=''                       ;;
	'14') pro___=''                       ; pro__s=''                       ;;
	'15') pro___=''                       ; pro__s=''                       ;;
	'16') pro___=''                       ; pro__s=''                       ;;
	'17') pro___=''                       ; pro__s=''                       ;;
	'18') pro___=''                       ; pro__s=''                       ;;
	'19') pro___=''                       ; pro__s=''                       ;;
	'20') pro___=''                       ; pro__s=''                       ;;
	'21') pro___=''                       ; pro__s=''                       ;;
	'22') pro___='<left>'                 ; pro__s='<home>'                 ;;
	'23') pro___='<right>'                ; pro__s='<end>'                  ;;
	'24') pro___='<up>'                   ; pro__s=''                       ;;
	'25') pro___='<down>'                 ; pro__s=''                       ;;
	'26') pro___=''                       ; pro__s=''                       ;;
	'27') pro___=''                       ; pro__s=''                       ;;
	'28') pro___=''                       ; pro__s=''                       ;;
	'29') pro___=''                       ; pro__s=''                       ;;
	'30') pro___='<tab>'                  ; pro__s='<s-tab>'                ;;
	'31') pro___='<backspace>'            ; pro__s=''                       ;;
	'32') pro___='<del>'                  ; pro__s=''                       ;;
	'33') pro___=''                       ; pro__s=''                       ;;
	'34') pro___='<esc>'                  ; pro__s=''                       ;;
	'35') pro___='<ret>'                  ; pro__s=''                       ;;
	'36') pro___='<left>'                 ; pro__s='<home>'                 ;;
	'37') pro___='<right>'                ; pro__s='<end>'                  ;;
	'38') pro___='<up>'                   ; pro__s=''                       ;;
	'39') pro___='<down>'                 ; pro__s=''                       ;;
	'40') pro___='<a-b>'                  ; pro__s='<a-B>'                  ;;
	'41') pro___='<a-e><right>'           ; pro__s='<a-E><right>'           ;;
	'42') pro___=''                       ; pro__s=''                       ;;
	'43') pro___=''                       ; pro__s=''                       ;;
	'44') pro___=''                       ; pro__s=''                       ;;
	'45') pro___=''                       ; pro__s=''                       ;;
	'46') pro___=''                       ; pro__s=''                       ;;
	'47') pro___=''                       ; pro__s=''                       ;;
	'48') pro___='<a-;>'                  ; pro__s='<esc>'                  ;;
	'49') pro___=''                       ; pro__s=''                       ;;
	'50') pro___=''                       ; pro__s=''                       ;;
	'51') pro___=''                       ; pro__s=''                       ;;
	'52') pro___='<c-v>'                  ; pro__s=''                       ;;
	'53') pro___=''                       ; pro__s=''                       ;;
	'54') pro___='<c-r>'                  ; pro__s='<c-y>'                  ;;
	'55') pro___=''                       ; pro__s=''                       ;;
	'56') pro___=''                       ; pro__s=''                       ;;
	'57') pro___=''                       ; pro__s=''                       ;;
	'58') pro___=''                       ; pro__s=''                       ;;
	'59') pro___=''                       ; pro__s=''                       ;;
	'60') pro___=''                       ; pro__s=''                       ;;
	'61') pro___=''                       ; pro__s=''                       ;;
	'62') pro___=''                       ; pro__s=''                       ;;
	'63') pro___=''                       ; pro__s=''                       ;;
	'64') pro___=''                       ; pro__s=''                       ;;
	'65') pro___=''                       ; pro__s=''                       ;;
	'66') pro___=''                       ; pro__s=''                       ;;
	'67') pro___='<c-o>'                  ; pro__s='<a-!>'                  ;;
	'68') pro___=''                       ; pro__s=''                       ;;
	'69') pro___=''                       ; pro__s=''                       ;;
	'70') pro___=''                       ; pro__s=''                       ;;
	'71') pro___=''                       ; pro__s=''                       ;;
	'72') pro___=''                       ; pro__s=''                       ;;

	 '0') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '1') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '2') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '3') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '4') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '5') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '6') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '7') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '8') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	 '9') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'10') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'11') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'12') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'13') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'14') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'15') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'16') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'17') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'18') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'19') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'20') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'21') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'22') men___='<;><G><i>'              ; men__s='<;><G><h>'              ; men_a_='<G><i>'                 ; men_as='<G><h>'                 ;;
	'23') men___='<;><G><l>'              ; men__s='<;><G><j>'              ; men_a_='<G><l>'                 ; men_as='<G><j>'                 ;;
	'24') men___='<;><G><g>'              ; men__s='<;><G><t>'              ; men_a_='<G><g>'                 ; men_as='<G><t>'                 ;;
	'25') men___='<;><G><e>'              ; men__s='<;><G><b>'              ; men_a_='<G><e>'                 ; men_as='<G><b>'                 ;;
	'26') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'27') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'28') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'29') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'30') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'31') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'32') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'33') men___=': bkey-to-line<ret>'    ; men__s=''                       ; men_a_=': bkey-to-line e<ret>'  ; men_as=''                       ;;
	'34') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'35') men___='<;><G><f>'              ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'36') men___='<;><G><i>'              ; men__s='<;><G><h>'              ; men_a_='<G><i>'                 ; men_as='<G><h>'                 ;;
	'37') men___='<;><G><l>'              ; men__s='<;><G><j>'              ; men_a_='<G><l>'                 ; men_as='<G><j>'                 ;;
	'38') men___='<;><G><g>'              ; men__s='<;><G><t>'              ; men_a_='<G><g>'                 ; men_as='<G><t>'                 ;;
	'39') men___='<;><G><e>'              ; men__s='<;><G><b>'              ; men_a_='<G><e>'                 ; men_as='<G><b>'                 ;;
	'40') men___='<c-u>'                  ; men__s='<c-b>'                  ; men_a_=''                       ; men_as=''                       ;;
	'41') men___='<c-d>'                  ; men__s='<c-f>'                  ; men_a_=''                       ; men_as=''                       ;;
	'42') men___='<a-*>'                  ; men__s='<*>'                    ; men_a_='<a-*><%><s><ret>'       ; men_as='<*><%><s><ret>'         ;;
	'43') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'44') men___='<t>'                    ; men__s='<a-t>'                  ; men_a_='<T>'                    ; men_as='<a-T>'                  ;;
	'45') men___='<;><G><f>'              ; men__s='<;><G><c>'              ; men_a_='<G><f>'                 ; men_as='<G><c>'                 ;;
	'46') men___='<a-z>'                  ; men__s='<a-Z>'                  ; men_a_=''                       ; men_as=''                       ;;
	'47') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'48') men___='<a-s>'                  ; men__s='<a-S>'                  ; men_a_=''                       ; men_as=''                       ;;
	'49') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'50') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'51') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'52') men___='<s>'                    ; men__s='<S>'                    ; men_a_=''                       ; men_as=''                       ;;
	'53') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'54') men___='<@>'                    ; men__s='<a-@>'                  ; men_a_=''                       ; men_as=''                       ;;
	'55') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'56') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'57') men___=': bkey-ins pa<ret>'     ; men__s='<a-R>'                  ; men_a_=': bkey-ins pea<ret>'    ; men_as=''                       ;;
	'58') men___='<a-k>'                  ; men__s='<a-K>'                  ; men_a_=''                       ; men_as=''                       ;;
	'59') men___='<o>'                    ; men__s='<O>'                    ; men_a_=''                       ; men_as=''                       ;;
	'60') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'61') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'62') men___='<$>'                    ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'63') men___='<;><G><.>'              ; men__s='<;><G><a>'              ; men_a_='<G><.>'                 ; men_as='<G><a>'                 ;;
	'64') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'65') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'66') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'67') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'68') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'69') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'70') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'71') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;
	'72') men___=''                       ; men__s=''                       ; men_a_=''                       ; men_as=''                       ;;

	 '0') vie___=''                       ; vie__s=''                       ;;
	 '1') vie___=''                       ; vie__s=''                       ;;
	 '2') vie___=''                       ; vie__s=''                       ;;
	 '3') vie___=''                       ; vie__s=''                       ;;
	 '4') vie___=''                       ; vie__s=''                       ;;
	 '5') vie___=''                       ; vie__s=''                       ;;
	 '6') vie___=''                       ; vie__s=''                       ;;
	 '7') vie___=''                       ; vie__s=''                       ;;
	 '8') vie___=''                       ; vie__s=''                       ;;
	 '9') vie___=''                       ; vie__s=''                       ;;
	'10') vie___=''                       ; vie__s=''                       ;;
	'11') vie___=''                       ; vie__s=''                       ;;
	'12') vie___=''                       ; vie__s=''                       ;;
	'13') vie___=''                       ; vie__s=''                       ;;
	'14') vie___=''                       ; vie__s=''                       ;;
	'15') vie___=''                       ; vie__s=''                       ;;
	'16') vie___=''                       ; vie__s=''                       ;;
	'17') vie___=''                       ; vie__s=''                       ;;
	'18') vie___=''                       ; vie__s=''                       ;;
	'19') vie___=''                       ; vie__s=''                       ;;
	'20') vie___=''                       ; vie__s=''                       ;;
	'21') vie___=''                       ; vie__s=''                       ;;
	'22') vie___='<v><h>'                 ; vie__s='99999<v><h>'            ;;
	'23') vie___='<v><l>'                 ; vie__s='99999<v><l>'            ;;
	'24') vie___='<v><k>'                 ; vie__s='<v><b>'                 ;;
	'25') vie___='<v><j>'                 ; vie__s='<v><t>'                 ;;
	'26') vie___=''                       ; vie__s=''                       ;;
	'27') vie___=''                       ; vie__s=''                       ;;
	'28') vie___=''                       ; vie__s=''                       ;;
	'29') vie___=''                       ; vie__s=''                       ;;
	'30') vie___=''                       ; vie__s=''                       ;;
	'31') vie___=''                       ; vie__s=''                       ;;
	'32') vie___=''                       ; vie__s=''                       ;;
	'33') vie___=''                       ; vie__s=''                       ;;
	'34') vie___=''                       ; vie__s=''                       ;;
	'35') vie___=''                       ; vie__s=''                       ;;
	'36') vie___='<v><h>'                 ; vie__s='99999<v><h>'            ;;
	'37') vie___='<v><l>'                 ; vie__s='99999<v><l>'            ;;
	'38') vie___='<v><k>'                 ; vie__s='<v><b>'                 ;;
	'39') vie___='<v><j>'                 ; vie__s='<v><t>'                 ;;
	'40') vie___='<c-u>'                  ; vie__s='<c-b>'                  ;;
	'41') vie___='<c-d>'                  ; vie__s='<c-f>'                  ;;
	'42') vie___=''                       ; vie__s=''                       ;;
	'43') vie___=''                       ; vie__s=''                       ;;
	'44') vie___=''                       ; vie__s=''                       ;;
	'45') vie___='<v><m>'                 ; vie__s='<v><c>'                 ;;
	'46') vie___=''                       ; vie__s=''                       ;;
	'47') vie___=''                       ; vie__s=''                       ;;
	'48') vie___=''                       ; vie__s=''                       ;;
	'49') vie___=''                       ; vie__s=''                       ;;
	'50') vie___=''                       ; vie__s=''                       ;;
	'51') vie___=''                       ; vie__s=''                       ;;
	'52') vie___=''                       ; vie__s=''                       ;;
	'53') vie___=''                       ; vie__s=''                       ;;
	'54') vie___=''                       ; vie__s=''                       ;;
	'55') vie___=''                       ; vie__s=''                       ;;
	'56') vie___=''                       ; vie__s=''                       ;;
	'57') vie___=''                       ; vie__s=''                       ;;
	'58') vie___=''                       ; vie__s=''                       ;;
	'59') vie___=''                       ; vie__s=''                       ;;
	'60') vie___=''                       ; vie__s=''                       ;;
	'61') vie___=''                       ; vie__s=''                       ;;
	'62') vie___=''                       ; vie__s=''                       ;;
	'63') vie___=''                       ; vie__s=''                       ;;
	'64') vie___=''                       ; vie__s=''                       ;;
	'65') vie___=''                       ; vie__s=''                       ;;
	'66') vie___=''                       ; vie__s=''                       ;;
	'67') vie___=''                       ; vie__s=''                       ;;
	'68') vie___=''                       ; vie__s=''                       ;;
	'69') vie___='<V><c><m><esc>'         ; vie__s=''                       ;;
	'70') vie___=''                       ; vie__s=''                       ;;
	'71') vie___=''                       ; vie__s=''                       ;;
	'72') vie___=''                       ; vie__s=''                       ;;


for i in {0..72}; do
	                             mapping+="map global normal         <${list[$i,1]}>   '${list[$i,3]}'       ;"
	                             mapping+="map global normal         <${list[$i,2]}>   '${list[$i,4]}'       ;"
	                             mapping+="map global normal         <a-${list[$i,1]}> '${list[$i,5]}'       ;"
	                             mapping+="map global normal         <a-${list[$i,2]}> '${list[$i,6]}'       ;"
	[[ ! -z ${list[$i,6]}  ]] && mapping+="map global normal         <c-${list[$i,1]}> '${list[$i,7]}'       ;"
	[[ ! -z ${list[$i,7]}  ]] && mapping+="map global normal         <c-${list[$i,2]}> '${list[$i,8]}'       ;"
	                             mapping+="map global insert         <a-${list[$i,1]}> '<a-;>${list[$i,3]}'  ;"
	                             mapping+="map global insert         <a-${list[$i,2]}> '<a-;>${list[$i,4]}'  ;"

	[[ ! -z ${list[$i,9]}  ]] && mapping+="map global insert         <a-${list[$i,1]}> '${list[$i,9]}'       ;"
	[[ ! -z ${list[$i,10]} ]] && mapping+="map global insert         <a-${list[$i,2]}> '${list[$i,10]}'      ;"

	                             mapping+="map global prompt         <a-${list[$i,1]}> '${list[$i,11]}'      ;"
	                             mapping+="map global prompt         <a-${list[$i,2]}> '${list[$i,12]}'      ;"

	[[ ! -z ${list[$i,13]} ]] && mapping+="map global Menu          <${list[$i,1]}>   '${list[$i,13]}'       ;" \
	                          && mapping+="map global MenuEx        <${list[$i,1]}>   '${list[$i,13]}'       ;"
	[[ ! -z ${list[$i,14]} ]] && mapping+="map global Menu          <${list[$i,2]}>   '${list[$i,14]}'       ;" \
	                          && mapping+="map global MenuEx        <${list[$i,2]}>   '${list[$i,14]}'       ;"
	[[ ! -z ${list[$i,15]} ]] && mapping+="map global Menu          <a-${list[$i,1]}> '${list[$i,15]}'       ;" \
	                          && mapping+="map global MenuEx        <${list[$i,1]}>   '${list[$i,15]}'       ;"
	[[ ! -z ${list[$i,16]} ]] && mapping+="map global Menu          <a-${list[$i,2]}> '${list[$i,16]}'       ;" \
	                          && mapping+="map global MenuEx        <${list[$i,2]}>   '${list[$i,16]}'       ;"

	[[ ! -z ${list[$i,17]} ]] && mapping+="map global View           <${list[$i,1]}>   '${list[$i,17]}'      ;"
	[[ ! -z ${list[$i,18]} ]] && mapping+="map global View           <${list[$i,2]}>   '${list[$i,18]}'      ;"
done

echo $mapping
